name: docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Run docker build to make sure it works
        run: |
          docker-compose build web

      - name: Run tests in docker to make sure they work
        run: |
          docker-compose exec web rspec spec
